### ISSUE TITLE
Error during traceback

### ISSUE THREAD

**Issue by jtodom04** [adeshpande3/March-Madness-ML#1]
`Traceback (most recent call last):
  File "DataPreprocessing.py", line 11, in <module>
    import pandas as pd
ImportError: No module named pandas
`
Help? Thanks. Look forward to using this.

**Comment by jtodom04** [comment]
I cant find the module. Did someone delete it? Going to try removing the traceback for myself.

**Comment by jtodom04** [comment]
Deleted panda line, but there is a missing file; DataPreprocessing.py

**Comment by adeshpande3** [comment]
Pandas is a Python library that you need to install. You can view the instructions [here](https://pandas.pydata.org/pandas-docs/stable/install.html). The best way normally is to run `pip install pandas` in your terminal.

**Comment by jtodom04** [comment]
Wow, didn't even look at the requirements. Thank you.
