### ISSUE TITLE
Illegal Instruction 4 when running MarchMadness.py

### ISSUE THREAD

**Issue by grhansen** [adeshpande3/March-Madness-ML#11]
I followed your instructions to get everything setup. I was able to run the DataPreprocessing.py fine, but when I try and run the MarchMadness script, I'm getting an execution error.  Any idea what the issue might be? I'm not real familiar with debugging python.

```
Shape of xTrain: (131372, 17)
Shape of yTrain: (131372,)
MacBook-Pro:March-Madness-ML$ pipenv run python MarchMadness.py 
Using TensorFlow backend.
Illegal instruction: 4
```

**Comment by grhansen** [comment]
looks like my mac is too old to run some of the new libraries. I'll figure out  how to get the correct libraries installed. This isn't an issue on your side.  Thanks for the library, by the way!

**Comment by adeshpande3** [comment]
Do you know which libraries are causing the problem? It's not really necessary to import all [these lines](https://github.com/adeshpande3/March-Madness-ML/blob/master/MarchMadness.py#L10-L42). Just depends on what type of model you want to run.

**Comment by grhansen** [comment]
@adeshpande3 - I just installed the software on my Ubuntu machine and it worked just fine. My Mac is really old, so it's nbd. Thanks for the reply. I really enjoyed using your software.
