### ISSUE TITLE
Incorrect Shape / Data Processing Issue

### ISSUE THREAD

**Issue by rshtirmer** [adeshpande3/March-Madness-ML#2]
After running through DataProcessing with the input "2019," I receive the following output: 
```
('Finished year:', 2019)    
('Shape of xTrain:', (0, 17))  
('Shape of yTrain:', (0,))
```

Expectedly, running MarchMadness.py on this data set results in the following:
`ValueError: Found array with 0 sample(s) (shape=(0, 17)) while a minimum of 1 is required.`

Best,
Ryan

**Comment by rshtirmer** [comment]
Update: I noticed you made some changes, so I'm running through DataProcessing right now. Looks like there's a lot more going on, which is hopeful. Will update later.

**Comment by rshtirmer** [comment]
Sorry, just noticed RatingStats_2019.csv ended up in RegSeasonStats folder which seems odd. Wanted to let you know.

**Comment by adeshpande3** [comment]
So the reason you're seeing that is that Kaggle dataset RegularSeasonCompactResults.csv didn't include this season's (2019) college basketball games. Unfortunate, but if you run DataProcessing.py you should get around 120,000 training examples from years 1993 to 2018 right? And so even though we don't get those games in the dataset, we can still get the team vectors and those 2019 team vectors should get saved, and then you'll be able to run MarchMadness.py

**Comment by rshtirmer** [comment]
Awesome, thanks! I just cloned again, since it looks like you made some more file tweaks, going to run DataProc.py again 👍

**Comment by rshtirmer** [comment]
Odd, here's the new output for MarchMadness.py 

```
('Shape of xTrain:', (126047, 17))
('Shape of yTrain:', (126047,))
What year are these predictions for?
2019
Traceback (most recent call last):
  File "MarchMadness.py", line 179, in <module>
    trainedModel = trainModel()
  File "MarchMadness.py", line 152, in trainModel
    model.fit(xTrain, yTrain)
  File "/usr/local/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py", line 979, in fit
    X, y = check_X_y(X, y, accept_sparse=['csr', 'csc', 'coo'], dtype=DTYPE)
  File "/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 453, in check_array
    _assert_all_finite(array)
  File "/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

**Comment by adeshpande3** [comment]
Hmm darn, I think I messed something up when I was trying to clean up the code in DataProcessing. I'll try to take a look later. In the meantime, I'm pretty sure [this version](https://github.com/adeshpande3/March-Madness-ML/blob/6f65fe1e5334ede83017cf9006318960e86f3a10/DataPreprocessing.py) of DataProcessing should work.

**Comment by rshtirmer** [comment]
Thanks, will give it a shot

**Comment by adeshpande3** [comment]
New version of DataProcessing that I just pushed up should work.
