### ISSUE TITLE
error on installing package dependencies

### ISSUE THREAD

**Issue by hacker-hippo** [adeshpande3/March-Madness-ML#6]
`An error occurred while installing gast==0.2.2 --hash=sha256:fe939df4583692f0512161ec1c880e0a10e71e6a232da045ab8edd3756fbadf0! Will try again.`

**Comment by adeshpande3** [comment]
What installation command were you trying to run?

**Comment by jtodom04** [comment]
pipenv

**Comment by jtodom04** [comment]
`cd March-Madness-ML`
`pipenv install`

**Comment by slimeate** [comment]
I'm not sure either. I tried installing from scratch a few times and couldn't reproduce the issue. I'm using
* pipenv version 2018.11.26 (installed through brew)
* python 3.7.2 (installed through pyenv)

@jtodom04 could you give us some more detail? Perhaps your pipenv and python versions. Also pasting the entirety of the output from `pipenv install` might help us figure this out.
